### ISSUE TITLE
Update markers when calling jMapping('update')

### ISSUE THREAD

**Issue by tra** [vigetlabs/jmapping#1]
I am building an application where the markers may be updated on the map dynamically.   But when I call jMapping('update') the markers don't change color as I hoped.

**Comment by tra** [comment]
I figured out what the problem is.   The metadata is cached by default.   I fixed this by overriding the cache behavior for place data.  See the change here:

http://github.com/tra/jmapping/commit/b1affe10c746038653efdeafcee1b5f65fee3edc

**Comment by brianjlandau** [comment]
I did a slightly different solution, so that is only happens when jMapping is actually being updated. You can grab it in the latest version 1.4.0
