### ISSUE TITLE
Event example?

### ISSUE THREAD

**Issue by mysterycommand** [vigetlabs/jmapping#15]
I've been trying to get events to work. I want to manipulate the map as soon as the page loads, but the map isn't ready (I get a "bounds is undefined" error) … I was hoping I could add a callback to the "afterMapping.jMapping" event, but I don't receive the event no matter where I try to bind it. I have tried:

$('#map').bind('afterMapping.jMapping', function(event) …
$('#map').bind('afterMapping', function(event) …

$('#map').jMapping().bind('afterMapping.jMapping', function(event) …
$('#map').jMapping().bind('afterMapping', function(event) …

$('#map').data('jMapping').bind('afterMapping.jMapping', function(event) …
$('#map').data('jMapping').bind('afterMapping', function(event) …

window.bind('afterMapping.jMapping', function(event) …
window.bind('afterMapping', function(event) …

The function is never called no matter what I try. Any help?

Thanks,
//Matt Hayes

**Comment by mysterycommand** [comment]
Bump!

**Comment by scharfie** [comment]
I think you want this:

``` javascript
$(document).bind('afterMapping.jMapping', function(event) {
  // do stuff
});

$('#map').jMapping();
```

**Comment by mysterycommand** [comment]
Hi scharfie,

Thanks for the suggestion, but it's still not working for me … though now I am able to log the event! My problem now is that I have several UI elements effecting the visibility of map locations, and I'm not sure what order these UI elements will be triggered in. For example, there is a "filter" system in place that narrows the set of map location, and alongside the filtering functionality there's a paginator plugin that effects which/how many map locations are visible. Also, there's a browser history plugin that might effect the initial state of map on page load.

Because of all this I have a function:

``` javascript
function updateMap()
{
    $map = $map || $("#map").jMapping({location_selector : '.map-location:visible'});
    try { $map.jMapping('update'); } catch(error) { /* console.log(error); */ }
}
```

This gets called on any change to the UI elements, and I believe it should initialize the map (if it isn't already), and then update it. When I add the event binding to my script like so:

``` javascript
$(document).bind('afterMapping.jMapping', function(event)
{
    console.log(event, this, $map, $("#map").data());
    if($('.map-location:visible').size() !== size($map.data('jMapping').gmarkers))
    {
        updateMap();
    }
});
```

The log traces 'undefined' for $map, and an empty object (save for the **proto** property) for $("#map").data().

How can $map be undefined if it's dispatching events? Some kind of scope/context thing I don't understand? All my codes are inside an anonymous self-executing function, and a $(document).ready() call … var $map and the binding are declared within the same scope so I don't see how I don't have access to $map. Any thoughts on any of this?

Thanks much,
//Matt Hayes

**Comment by scharfie** [comment]
You won't have access to $map outside of updateMap() unless it's global.  And if it is global, that's sort of a no-no ;)

If you need access to the jMapping api object within the jMapping callbacks, try this:

``` javascript
  var api = $('#map').data('jMapping'); // access to jMapping api object
  var gmap = api.map; // access to google map object
```

**Comment by mysterycommand** [comment]
Yeah, so everything is in a closure which I think should keep it out of the global namespace. Including only the relevant stuff, it looks like this:

``` javascript
;(function($, window, undefined) {

  $(function() {

    var $map;
    function updateMap() { /* as above */ }
    $(document).bind('afterMapping.jMapping', function(event) { /* as above */ });

  });

})(jQuery, this);
```

… so I don't think the scope of `$map` is the issue. And anyway, I get `undefined` if I try to access `$('#map').data('jMapping')` from inside the `afterMapping` handler.

**Comment by mysterycommand** [comment]
Okay, so I sort of got it working … I noticed on the jMapping documentation that it'll pass the api as a second argument to the event handler, so now I have something like this:

``` javascript
$(document).bind('afterMapping.jMapping', function(event, api)
{
    console.log(event.type, api, api.gmarkersArray().length);
});

$(document).bind('afterUpdate.jMapping', function(event, api)
{
    console.log(event.type, api, api.gmarkersArray().length);
});
```

Unfortunately, the `api.gmarkersArray().length` does not reflect what I can see on the screen. Huh!? In my case I'm paginating my results, so there should never be more than 10 markers on the map. `api.gmarkersArray().length` never returns more than 10 … EVEN WHEN I CAN SEE, AND COUNT, WITH MY EYES THAT THERE ARE MORE THAN 10 MARKERS ON THE MAP!!!

Anyway, looks like it's not jMapping's fault, but more of an issue with the Google Maps API.

Thanks for all your help!
