### ISSUE TITLE
default_zoom_level option doesn't seem to work

### ISSUE THREAD

**Issue by swrobel** [vigetlabs/jmapping#4]
Using default_zoom_level doesn't seem to affect the map. With 1 or no points it is at the highest zoom level, always. I've also tried force_zoom_level. Options do work, however, as I am able to set the default point and have the map center on it. I know that it's recognizing the option because I see it when I inspect the jmapping object, but it doesn't seem to affect the way the map is rendered.

**Comment by thkro** [comment]
Did you get this to work? I am having the same issue but not sure if I am using it properly.

**Comment by swrobel** [comment]
No, it doesn't seem to work.

**Comment by jeperkins4** [comment]
I am also experiencing this issue

**Comment by brianjlandau** [comment]
I've pushed a change that fixes this. And created a working example in the docs.
